version: '3.8'

services:
  manga-assistant:
    build: .
    ports:
      - "2828:8080"
    volumes:
      - ./manga-library:/manga-library
      - mangaassistant_manga_library:/mnt/manga
    environment:
      - MANGA_LIBRARY_PATH=/mnt/manga
    restart: unless-stopped

  frontend:
    image: node:18
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm start"

volumes:
  go-modules:
  mangaassistant_manga_library:
    driver: local
    driver_opts:
      type: none
      device: /c/Users/jason.mesisco/Downloads/Manga
      o: bind 